package com.example.kotlin_2.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.*

//When one goal is set active, we use the goal data to create a daily data

@Entity
data class DailyStatus(
    var currentSteps: Int,
    //todayDate will be generated by us (not by users) everytime when first create the this instance
    val todayDate: Date,
    @PrimaryKey(autoGenerate = true) val id:Int,
    var goalId: Int
)
